"""Deploy a Genie Space config to Databricks."""

from __future__ import annotations

import json
import logging

from genie_world.core.auth import get_workspace_client
from genie_world.core.tracing import trace

logger = logging.getLogger(__name__)

_MAX_SERIALIZED_SIZE = 3_500_000  # 3.5 MB


@trace(name="create_space", span_type="CHAIN")
def create_space(
    config: dict,
    display_name: str,
    warehouse_id: str,
    parent_path: str,
    description: str | None = None,
) -> dict:
    """Deploy a config to Databricks as a new Genie Space.

    Returns {"space_id": "...", "display_name": "...", "space_url": "..."}.
    """
    if not display_name or not display_name.strip():
        raise ValueError("Display name is required")

    display_name = display_name.strip()

    if not parent_path.endswith("/"):
        parent_path += "/"

    serialized = json.dumps(config)

    if len(serialized) > _MAX_SERIALIZED_SIZE:
        size_mb = len(serialized) / (1024 * 1024)
        raise ValueError(
            f"Serialized config is {size_mb:.1f} MB, exceeds 3.5 MB limit. "
            "Reduce the number of tables, examples, or benchmarks."
        )

    client = get_workspace_client()
    host = (client.config.host or "").rstrip("/")

    logger.info("Creating Genie Space '%s' at %s", display_name, parent_path)

    try:
        response = client.api_client.do(
            method="POST",
            path="/api/2.0/genie/spaces",
            body={
                "title": display_name,
                "description": description or "Genie Space generated by genie-world",
                "parent_path": parent_path,
                "warehouse_id": warehouse_id,
                "serialized_space": serialized,
            },
        )

        space_id = response.get("space_id")
        if not space_id:
            raise ValueError(f"API did not return space_id: {response}")

        space_url = f"{host}/genie/rooms/{space_id}"
        logger.info("Created Genie Space: %s", space_url)

        return {
            "space_id": space_id,
            "display_name": display_name,
            "space_url": space_url,
        }

    except Exception as e:
        error_str = str(e).lower()
        if "403" in error_str or "permission" in error_str:
            raise PermissionError(
                "Cannot create Genie Space. Ensure write permission to the target directory."
            )
        elif "400" in error_str or "invalid" in error_str:
            raise ValueError(f"Invalid configuration: {e}")
        else:
            raise
